#!/bin/bash

# Kolla om terminalen är startad
terminal_windows=$(xdotool search --onlyvisible --class gnome-terminal)

if [ -z "$terminal_windows" ]; then
    gnome-terminal
else
    focused_window_id=$(xdotool getwindowfocus)
    focused_window_name=$(xdotool getwindowname $focused_window_id)

    if [ "$focused_window_name" = "Terminal" ]; then
        xdotool windowminimize $focused_window_id
    else
        xdotool search --onlyvisible --class gnome-terminal windowactivate --sync
    fi
fi
