#!/bin/bash

# Ensure root
sudo -v

# Find PID of discord
pid=$(pidof Discord | rev | cut -d' ' -f-1 | rev)

# Stop Discord if running
if [ -n "$pid" ]; then
    echo "Stopping Discord."
    kill $pid
else
    echo "Discord is not running."
fi

# Remove old file if exists
if [ -e "/tmp/discord-latest.deb" ]; then
    echo "Removing old deb file."
	sudo rm "/tmp/discord-latest.deb"
fi

# Download latest version
curl -L "https://discord.com/api/download/stable?platform=linux&format=deb" -o "/tmp/discord-latest.deb"

# Install if file was downloaded successfully
if [ -e "/tmp/discord-latest.deb" ]; then
    sudo dpkg --install /tmp/discord-latest.deb
    sudo rm "/tmp/discord-latest.deb"
else
    echo "Could not locate /tmp/discord-latest.deb."
fi

